feat(REACTTODO-32): styling dark and light mode
macopul/Todo-App-React pull request #22
Opened 2023-11-22 11:14 UTC by macopul

2023-11-23 23:40 UTC, woopul requested changes

2023-11-23 23:40 UTC, woopul commented on src/themeMode/ThemeMode.tsx
> +import { THEME_MODE_KEY } from '../constants/storage';
Move this file to config directory
As it is **not** a react component, name it by lowercase

2023-11-23 23:40 UTC, woopul commented on src/components/themeModeIcon/themeModeIcon.tsx
> +import styles from './themeModeIcon.module.scss';
Component should be named uppercase - ThemeModeIcon

2023-11-23 23:40 UTC, woopul commented on src/components/themeModeIcon/themeModeIcon.tsx
> +  const handleOnclick = () => {
handleOn what click ?
Names should suggest what this should be doing
hadndleChangeTheme or handleOnChangeThemeButtonClick

2023-11-23 23:40 UTC, woopul commented on src/components/themeModeIcon/themeModeIcon.tsx
> +import styles from './themeModeIcon.module.scss';
Besides - this is not component which is only displaying icon..
more ThemeButton

2023-11-23 23:40 UTC, woopul commented on src/themeMode/ThemeMode.tsx
> +};
these 2 methods are redundand
You can create only 1 - toggleTheme() - which will change dark if white, and white if current is dark

2023-11-24 10:17 UTC, macopul commented on src/components/ThemeMode/ThemeMode.module.scss
> +}
I changed file name to upper case

2023-11-24 10:17 UTC, macopul commented on src/components/ThemeMode/ThemeMode.tsx
> +export default ThemeModeIcon;
Changed file name to upper case because it is a component

2023-11-24 10:20 UTC, macopul commented on src/components/ThemeMode/ThemeMode.tsx
> +export default ThemeMode;
changed to upper case

2023-11-24 10:21 UTC, macopul commented on src/config/themeMode/themeModeStorage.tsx
> +};
changed to toggle function

2023-11-29 21:38 UTC, woopul approved these changes

2023-11-29 21:38 UTC, woopul commented on src/config/themeMode/themeModeStorage.tsx
> +export const getIsDarkMode = () => {
if that's getter i would name it getTheme and then check neccessary if we'd have more than dark|light i.e getTheme === 'dark' ?
If you want to have theme specific check function I would call it isDarkTheme()

2023-11-29 21:41 UTC, woopul approved these changes

2023-11-29 21:41 UTC, woopul commented on src/components/ThemeMode/ThemeMode.tsx
> +const ThemeMode = () => {
This is Button or Section underneath - I would call it ThemeButton / ThemeSwitcher / ThemeModeSwither /ThemeSelector - anything that sugggest action

2023-11-29 21:45 UTC, woopul commented on src/components/ThemeMode/ThemeMode.tsx
> +  const handleOnclick = () => {
handleOnClick is still not changed - handleOn(What??)Click ?

Name handlers the way that when you read them - you have an idea what theire for.
i.e hadleThemeButtonClick / handleToggleTheme / handleThemeSwitch

2023-12-06 14:19 UTC, merged